Category.create!([
  {name: "20-minute meals"},
  {name: "American"},
  {name: "Apple season"},
  {name: "Asian"},
  {name: "Asparagus"},
  {name: "Baking"},
  {name: "Bbq"},
  {name: "Beef"},
  {name: "Berry season"},
  {name: "Bread"},
  {name: "Breakfast"},
  {name: "British"},
  {name: "Brunch recipes"},
  {name: "Cake"},
  {name: "Casseroles"},
  {name: "Chicken"},
  {name: "Chinese"},
  {name: "Chocolate"},
  {name: "Christmas"},
  {name: "Christmas bakery"},
  {name: "Cocktails"},
  {name: "Comfort food"},
  {name: "Cookies"},
  {name: "Dessert"},
  {name: "Dinner party"},
  {name: "Drink"},
  {name: "Easter"},
  {name: "European"},
  {name: "Family favorites"},
  {name: "Finger food"},
  {name: "Fourth of july"},
  {name: "French"},
  {name: "Frozen treats"},
  {name: "Game day"},
  {name: "German"},
  {name: "Greek"},
  {name: "Indian"},
  {name: "Italian"},
  {name: "Jewish"},
  {name: "Low carb"},
  {name: "Main course"},
  {name: "Main"},
  {name: "Mardi gras"},
  {name: "Meatless"},
  {name: "Mediterranean"},
  {name: "Mexican"},
  {name: "Middle-eastern"},
  {name: "Mother's day"},
  {name: "No-bake desserts"},
  {name: "One-pot"},
  {name: "Packed lunch"},
  {name: "Pasta"},
  {name: "Pies and tarts"},
  {name: "Pizza"},
  {name: "Potatoes"},
  {name: "Potluck"},
  {name: "Prep ahead"},
  {name: "Pumpkin"},
  {name: "Quick bites"},
  {name: "Quick dessert"},
  {name: "Recipes for fall"},
  {name: "Recipes for spring"},
  {name: "Recipes for summer"},
  {name: "Recipes for winter"},
  {name: "Refreshments"},
  {name: "Salads"},
  {name: "Seafood"},
  {name: "Soup"},
  {name: "Snack"},
  {name: "Starter"},
  {name: "Strawberry season"},
  {name: "Thanksgiving"},
  {name: "Under 400 calories"},
  {name: "Under 7 ingredients"},
  {name: "Valentine's day"},
  {name: "Vegan"},
  {name: "Vegetarian"},
  {name: "Vietnamese"},
  {name: "Wedding season"},
  {name: "Weeknight dinners"}
])
Cuisine.create!([
  {sort: "Traditional", country: "China"},
  {sort: "Traditional", country: "Italy"},
  {sort: "Traditional", country: "India"},
  {sort: "Traditional", country: "Spain"},
  {sort: "Traditional", country: "America"},
  {sort: "Traditional", country: "East"},
  {sort: "Traditional", country: "Asia"},
  {sort: "Traditional", country: "France"},
  {sort: "Traditional", country: "Europe"},
  {sort: "Traditional", country: "Pakistan"},
  {sort: "Traditional", country: "Korea"},
  {sort: "Traditional", country: "Russia"},
  {sort: "Traditional", country: "Greece"},
  {sort: "East", country: "Africa"},
  {sort: "Other", country: "Other"},

  Cuisine.last.update_all(id: 1000)
])
Diet.create!([
  {name: "Regular"},
  {name: "Low-fat"},
  {name: "Vegetarian"},
  {name: "Vegan"},
  {name: "Sugar-free"},
  {name: "Lactose-free"},
  {name: "Gluten-free"},
  {name: "Alcohol-free"}
])
Difficulty.create!([
  {level: "Easy"},
  {level: "Medium"},
  {level: "Hard"}
])
Ingredient.create!([
  {name: "spice"},
  {name: "almond"},
  {name: "all-purpose flour"},
  {name: "amaretti"},
  {name: "anchovy"},
  {name: "anise"},
  {name: "apple juice"},
  {name: "artichoke"},
  {name: "artichoke heart"},
  {name: "artichoke"},
  {name: "asparagus"},
  {name: "asparagus spear"},
  {name: "aubergine"},
  {name: "avocado"},
  {name: "bacon"},
  {name: "baguette"},
  {name: "baked beans"},
  {name: "balsamic vinegar"},
  {name: "bamboo"},
  {name: "banana"},
  {name: "bap"},
  {name: "basil"},
  {name: "bay leaf"},
  {name: "bay leaves"},
  {name: "bean"},
  {name: "beef"},
  {name: "beef mince"},
  {name: "beef brisket"},
  {name: "beef stock"},
  {name: "bell pepper"},
  {name: "berry"},
  {name: "berries"},
  {name: "bicarbonate of soda"},
  {name: "biscuit"},
  {name: "biscuit"},
  {name: "black olive"},
  {name: "black pepper"},
  {name: "black-eyed peas"},
  {name: "blueberries"},
  {name: "blueberry"},
  {name: "bonnet chilli"},
  {name: "bouillon"},
  {name: "bourbon"},
  {name: "braising steak"},
  {name: "bran"},
  {name: "brandy"},
  {name: "bread"},
  {name: "breadcrumbs"},
  {name: "bbq sauce"},
  {name: "habanero sauce"},
  {name: "brie"},
  {name: "brine"},
  {name: "broccoli"},
  {name: "brown rice"},
  {name: "brown sauce"},
  {name: "brown sugar"},
  {name: "buckwheat"},
  {name: "buffalo"},
  {name: "bun"},
  {name: "butter"},
  {name: "buttermilk"},
  {name: "butternut"},
  {name: "butternut squash"},
  {name: "butterscotch"},
  {name: "cabbage"},
  {name: "cake"},
  {name: "candy"},
  {name: "candies"},
  {name: "cannellini"},
  {name: "canola oil"},
  {name: "caper"},
  {name: "caramel"},
  {name: "caraway seed"},
  {name: "cardamom"},
  {name: "carrot"},
  {name: "carrot"},
  {name: "cashew"},
  {name: "caster sugar"},
  {name: "cayenne pepper"},
  {name: "celeriac"},
  {name: "celery"},
  {name: "cereal"},
  {name: "champagne"},
  {name: "chard"},
  {name: "cheddar cheese"},
  {name: "cheese"},
  {name: "cherries"},
  {name: "cherry"},
  {name: "cherry tomatoe"},
  {name: "chestnut"},
  {name: "chicken"},
  {name: "chicken breast"},
  {name: "chicken drumstick"},
  {name: "chicken stock"},
  {name: "chicken thigh"},
  {name: "chicken leg"},
  {name: "chicken"},
  {name: "chickpea"},
  {name: "chicory"},
  {name: "chile"},
  {name: "chilli"},
  {name: "chillies"},
  {name: "chipotle"},
  {name: "chip"},
  {name: "chive"},
  {name: "chive"},
  {name: "chocolate"},
  {name: "chop"},
  {name: "choy"},
  {name: "chutney"},
  {name: "ciabatta"},
  {name: "cider"},
  {name: "cinnamon"},
  {name: "clam"},
  {name: "clarified butter"},
  {name: "clove"},
  {name: "cocoa"},
  {name: "coconut"},
  {name: "orange essence"},
  {name: "almond essence"},
  {name: "coconut milk"},
  {name: "cod"},
  {name: "coffee"},
  {name: "coleslaw"},
  {name: "condensed milk"},
  {name: "coriander"},
  {name: "coriander leaves"},
  {name: "corn"},
  {name: "cornflour"},
  {name: "cornmeal"},
  {name: "courgette"},
  {name: "couscous"},
  {name: "cranberries"},
  {name: "cranberry"},
  {name: "cranberry juice"},
  {name: "cream"},
  {name: "single cream"},
  {name: "double cream"},
  {name: "sour cream"},
  {name: "creme fraiche"},
  {name: "crisp"},
  {name: "crust"},
  {name: "creme de cassis"},
  {name: "cucumber"},
  {name: "cumin"},
  {name: "custard"},
  {name: "dijon mustard"},
  {name: "dill"},
  {name: "duck"},
  {name: "edamame bean"},
  {name: "egg"},
  {name: "espresso"},
  {name: "fennel"},
  {name: "feta"},
  {name: "fig"},
  {name: "fillet steak"},
  {name: "filo pastry"},
  {name: "fish"},
  {name: "flank"},
  {name: "flour"},
  {name: "focaccia"},
  {name: "foie gras"},
  {name: "fruit"},
  {name: "fudge"},
  {name: "garam masala"},
  {name: "garlic"},
  {name: "gelatine"},
  {name: "gin"},
  {name: "ginger"},
  {name: "glucose"},
  {name: "goat"},
  {name: "goat's cheese"},
  {name: "golden syrup"},
  {name: "gorgonzola"},
  {name: "gouda"},
  {name: "grape"},
  {name: "grapefruit"},
  {name: "grape"},
  {name: "grapeseed"},
  {name: "green olive"},
  {name: "green pepper"},
  {name: "green"},
  {name: "gruyere"},
  {name: "gruyere cheese"},
  {name: "haddock"},
  {name: "ham"},
  {name: "harissa"},
  {name: "herbs"},
  {name: "hoisin"},
  {name: "hoisin sauce"},
  {name: "honey"},
  {name: "honeydew melon"},
  {name: "horseradish"},
  {name: "iceberg lettuce"},
  {name: "icing sugar"},
  {name: "jalapeno pepper"},
  {name: "juice"},
  {name: "julienne"},
  {name: "kalamata olives"},
  {name: "ketchup"},
  {name: "kidney bean"},
  {name: "lager"},
  {name: "lamb"},
  {name: "lard"},
  {name: "lardons"},
  {name: "lasagne"},
  {name: "lavender"},
  {name: "leek"},
  {name: "lemon"},
  {name: "lemongrass"},
  {name: "lentil"},
  {name: "lettuce"},
  {name: "lime"},
  {name: "limoncello"},
  {name: "lobster"},
  {name: "loin"},
  {name: "lychee"},
  {name: "macadamia nut"},
  {name: "malt"},
  {name: "mangetout"},
  {name: "mango"},
  {name: "mangoes"},
  {name: "maple syrup"},
  {name: "marinara"},
  {name: "marshmallow"},
  {name: "marzano"},
  {name: "mascarpone"},
  {name: "mayonnaise"},
  {name: "meat"},
  {name: "melon"},
  {name: "milk"},
  {name: "mince"},
  {name: "mint"},
  {name: "miso soup"},
  {name: "molasses"},
  {name: "monterey jack"},
  {name: "mozzarella"},
  {name: "mushroom"},
  {name: "mustard"},
  {name: "new potato"},
  {name: "noodle"},
  {name: "nutella"},
  {name: "nutmeg"},
  {name: "nut"},
  {name: "oat"},
  {name: "oil"},
  {name: "okra"},
  {name: "olive oil"},
  {name: "olive"},
  {name: "onion"},
  {name: "onion ring"},
  {name: "orange"},
  {name: "orange juice"},
  {name: "oregano"},
  {name: "oyster"},
  {name: "pak choi"},
  {name: "pancetta"},
  {name: "panko"},
  {name: "papaya"},
  {name: "paprika"},
  {name: "parma ham"},
  {name: "parmesan"},
  {name: "parmigiano"},
  {name: "parmigiano-reggiano"},
  {name: "parsley"},
  {name: "parsnip"},
  {name: "passion fruit"},
  {name: "pasta"},
  {name: "pasta shell"},
  {name: "pastry"},
  {name: "pea"},
  {name: "peach"},
  {name: "peaches"},
  {name: "peanut"},
  {name: "peanut"},
  {name: "pear"},
  {name: "pea"},
  {name: "pecan"},
  {name: "pecorino"},
  {name: "penne"},
  {name: "penne pasta"},
  {name: "pepper"},
  {name: "peppercorn"},
  {name: "peppers"},
  {name: "pesto"},
  {name: "pickle"},
  {name: "pickled gherkin"},
  {name: "pickled onion"},
  {name: "pickled red onion"},
  {name: "pie"},
  {name: "pimento pepper"},
  {name: "pine nut"},
  {name: "pineapple"},
  {name: "pistachio"},
  {name: "pita"},
  {name: "pitta"},
  {name: "pitted olive"},
  {name: "pizza"},
  {name: "plantain"},
  {name: "plum"},
  {name: "plum tomato"},
  {name: "plum tomatoes"},
  {name: "sun dried tomato"},
  {name: "poblano"},
  {name: "pod"},
  {name: "polenta"},
  {name: "pomegranate"},
  {name: "popcorn"},
  {name: "pork"},
  {name: "pork chop"},
  {name: "porridge"},
  {name: "poultry"},
  {name: "potato"},
  {name: "potatoes"},
  {name: "prawn"},
  {name: "prosciutto"},
  {name: "prosciutto ham"},
  {name: "provolone"},
  {name: "pumpkin"},
  {name: "quail"},
  {name: "radicchio"},
  {name: "radish"},
  {name: "radishes"},
  {name: "rapeseed oil"},
  {name: "raspberries"},
  {name: "raspberry"},
  {name: "red pepper"},
  {name: "red onion"},
  {name: "relish"},
  {name: "rhubarb"},
  {name: "rib"},
  {name: "rice"},
  {name: "ricotta"},
  {name: "rocket"},
  {name: "roll"},
  {name: "rose"},
  {name: "rosemary"},
  {name: "russet"},
  {name: "saffron"},
  {name: "sage"},
  {name: "sake"},
  {name: "salad"},
  {name: "salami"},
  {name: "salmon"},
  {name: "salmon flake"},
  {name: "salsa"},
  {name: "salt"},
  {name: "sauce"},
  {name: "sausage"},
  {name: "savoy cabbage"},
  {name: "scallop"},
  {name: "schnapps"},
  {name: "self raising flour"},
  {name: "semolina"},
  {name: "seafood"},
  {name: "serrano ham"},
  {name: "shallot"},
  {name: "shaohsing"},
  {name: "sherry"},
  {name: "shiitake"},
  {name: "shiitake mushroom"},
  {name: "shortcrust pastry"},
  {name: "sirloin"},
  {name: "sirloin steak"},
  {name: "slaw"},
  {name: "smoky bacon"},
  {name: "snapper"},
  {name: "sourdough"},
  {name: "soy sauce"},
  {name: "spaghetti"},
  {name: "spice"},
  {name: "spinach"},
  {name: "sponge"},
  {name: "spring onion"},
  {name: "sprout"},
  {name: "squash"},
  {name: "squid"},
  {name: "sriracha"},
  {name: "steak"},
  {name: "stock"},
  {name: "stout"},
  {name: "strawberries"},
  {name: "strawberry"},
  {name: "stuffing"},
  {name: "sugar"},
  {name: "sultana"},
  {name: "sunflower oil"},
  {name: "sweet pepper"},
  {name: "sweetcorn"},
  {name: "sweets"},
  {name: "swordfish"},
  {name: "tangerine"},
  {name: "tapioca"},
  {name: "tarragon"},
  {name: "tartar"},
  {name: "tea"},
  {name: "tequila"},
  {name: "thyme"},
  {name: "toast"},
  {name: "toffee"},
  {name: "tofu"},
  {name: "tomatillos"},
  {name: "tomato"},
  {name: "tomato puree"},
  {name: "tomatoes"},
  {name: "tortilla"},
  {name: "treacle"},
  {name: "tuna steak"},
  {name: "tuna"},
  {name: "turkey"},
  {name: "turkey breast"},
  {name: "turkey thigh"},
  {name: "turmeric"},
  {name: "turnip"},
  {name: "vanilla"},
  {name: "vanilla essence"},
  {name: "vanilla pod"},
  {name: "veal"},
  {name: "vegetable oil"},
  {name: "vermouth"},
  {name: "vinaigrette"},
  {name: "vinegar"},
  {name: "white wine vinegar"},
  {name: "red wine vinegar"},
  {name: "vodka"},
  {name: "waffle"},
  {name: "walnut"},
  {name: "watercress"},
  {name: "watermelon"},
  {name: "white rice"},
  {name: "wholegrain pasta"},
  {name: "wine"},
  {name: "worcestershire sauce"},
  {name: "yeast"},
  {name: "yellow pepper"},
  {name: "greek yoghurt"},
  {name: "natural yoghurt"},
  {name: "yoghurt"},
  {name: "yogurt"},
  {name: "red onion"},
  {name: "water"},
  {name: "powdered vegetable broth"},
  {name: "scallions"},
  {name: "sesame oil"},
  {name: "vanilla sugar"},
  {name: "baking powder"},
  {name: "bittersweet chocolate chips"},
  {name: "pizza dough"},
  {name: "tomato sauce"},
  {name: "chili"},
  {name: "red bell pepper"},
  {name: "yellow bell pepper"},
  {name: "cumin (ground)"},
  {name: "canned tomatoes"},
  {name: "vegetable broth"},
  {name: "lemon juice"},
  {name: "tomato juice"},
  {name: "tabasco"},
  {name: "ice cubes"},
  {name: "celery stick"},
  {name: "chicken legs"},
  {name: "curry powder"},
  {name: "crushed tomatoes canned"},
  {name: "lamb saddle"},
  {name: "pineapple juice"},
  {name: "mirin"},
  {name: "chilli pepper"},
  {name: "sesame seeds"},
  {name: "peas"},
  {name: "vegetable stock"},
  {name: "mint leaves"},
  {name: "spaghetti (gluten-free)"},
  {name: "cherry tomatoes"},
  {name: "arugula"},
  {name: "capers"},
  {name: "chicken (boneless)"},
  {name: "almonds"},
  {name: "green chili peppers"},
  {name: "white pepper"},
  {name: "chili powder"},
  {name: "parathas"},
  {name: "chinese cabbage"},
  {name: "sea salt"},
  {name: "dark rice vinegar"},
  {name: "chili pepper"},
  {name: "fish sauce"},
  {name: "red chili"},
  {name: "white cabbage"},
  {name: "parsley root"},
  {name: "marjoram"},
  {name: "white wine"},
  {name: "puff pastry"},
  {name: "egg yolk"},
  {name: "leeks"},
  {name: "cornstarch"},
  {name: "chicken flavor bouillon (powdered)"},
  {name: "peanut oil"},
  {name: "toasted sesame oil"},
  {name: "fried onions"},
  {name: "canned peaches"}
])

User.create!([
  {username: "2", password_digest: "$2a$10$k.8UHoa/a40p7Vb3tnDuN.OTSZx52S3TUra9TFaxhbaY9a/002PJ6", name: "Kate Jhonson", session_token: "LidWypT6OSY32v6_v6PuZw"},
  {username: "3", password_digest: "$2a$10$WCBjgsCoR/GtySF05o0eTeHPD4x8MhTQnHRMTN4whivWzu.Si50N.", name: "Stephen Luciani", session_token: "d4qouTewp-fkj0KOMGb3yA"},
  {username: "1", password_digest: "$2a$10$mAOlZxUw7Ur3tUXracf1FuweaklOb60mc.oQmb0B4E1Ks13MCHb/e", name: "Tom McAnderson", session_token: "EJXkgwvPfzVU71c5XYLnvA"},
  {username: "demo", password_digest: "$2a$10$kiBN4yrHoczHc12ZQJhz9O5w1DnEhRTJcATRUqRgQVFGCNE1TzSYu", name: "Demo User", session_token: "8S-iJI0Db_4eaN9GjXisWg"}
])

Measuring.create!([
  {name: "tablespoon"},
  {name: "teaspoon"},
  {name: "quart"},
  {name: "oz"},
  {name: "fl oz"},
  {name: "lb"},
  {name: "cup"},
  {name: "pcs"},
  {name: "clove"},
  {name: "cluster"},
  {name: "pinch"},
  {name: "slice"},
  {name: "leaf"},
  {name: "drop"},
  {name: "stick"},
  {name: "wedge"},
  {name: "bottle"},
  {name: "can"}
])

Recipe.create!([
  {author_id: 4, title: "Light broccoli soup", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532970342/bhljojz4qzaeswfkjcrt.jpg", cooking_time: 25, difficulty_id: 1, cuisine_id: 3, category_id: 70, main_ingredient_id: 53, diet_id: 3},
  {author_id: 4, title: "Egg drop soup", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532970973/mwqqfut9xjxkqwnzu5rl.jpg", cooking_time: 15, difficulty_id: 1, cuisine_id: 1, category_id: 42, main_ingredient_id: 151, diet_id: 2},
  {author_id: 4, title: "Easy chocolate loaf cake", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532971520/ebp8lx8rokwxiqpu3lyy.jpg", cooking_time: 105, difficulty_id: 1, cuisine_id: 9, category_id: 24, main_ingredient_id: 60, diet_id: 1},
  {author_id: 4, title: "Pizza waffles", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532972586/rtqvizbodwjshvaxdz2m.jpg", cooking_time: 20, difficulty_id: 1, cuisine_id: 5, category_id: 69, main_ingredient_id: 448, diet_id: 1},
  {author_id: 4, title: "Shakshuka", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532972895/rleqdkxuwialzs2vuvxm.jpg", cooking_time: 45, difficulty_id: 1, cuisine_id: 6, category_id: 11, main_ingredient_id: 250, diet_id: 2},
  {author_id: 4, title: "Bloody mary", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532973850/t0r51kf7vb3ivlxklg3h.jpg", cooking_time: 5, difficulty_id: 1, cuisine_id: 9, category_id: 26, main_ingredient_id: 456, diet_id: 4},
  {author_id: 4, title: "East african-style coconut chicken", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532974705/o5f3drbfk3ggrhnewky4.jpg", cooking_time: 45, difficulty_id: 2, cuisine_id: 11, category_id: 16, main_ingredient_id: 461, diet_id: 1},
  {author_id: 4, title: "Teriyaki lamb skewers with pea-mint-puree", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532975680/bu9naulcuvgzerjd6wrz.jpg", cooking_time: 60, difficulty_id: 2, cuisine_id: 6, category_id: 29, main_ingredient_id: 464, diet_id: 1},
  {author_id: 4, title: "Gluten-free spaghetti with tomatoes and arugula", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532976361/cx6sjojujodjzs00rfkb.jpg", cooking_time: 15, difficulty_id: 1, cuisine_id: 2, category_id: 80, main_ingredient_id: 472, diet_id: 7},
  {author_id: 4, title: "Chicken malai boti", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532977227/kri8nijwhlsaszv6fbyp.jpg", cooking_time: 205, difficulty_id: 1, cuisine_id: 12, category_id: 73, main_ingredient_id: 476, diet_id: 2},
  {author_id: 4, title: "Homemade shortcut kimchi", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532978666/yuoetzawuuulpml80ius.jpg", cooking_time: 15, difficulty_id: 1, cuisine_id: 13, category_id: 40, main_ingredient_id: 482, diet_id: 3},
  {author_id: 4, title: "Russian cabbage soup", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532979052/pna2dnipjfyjuhqysmol.jpg", cooking_time: 200, difficulty_id: 1, cuisine_id: 14, category_id: 28, main_ingredient_id: 26, diet_id: 1},
  {author_id: 1, title: "Beef wellington", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532983711/bumk13ifrzpeplfke4vk.jpg", cooking_time: 80, difficulty_id: 3, cuisine_id: 9, category_id: 8, main_ingredient_id: 26, diet_id: 1},
  {author_id: 1, title: "Pork and leek stir-fry", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532984657/zomlebxjcjaulg7whk0p.jpg", cooking_time: 40, difficulty_id: 1, cuisine_id: 7, category_id: 4, main_ingredient_id: 309, diet_id: 1},
  {author_id: 1, title: "Chicken salad with crispy onions and sesame", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532985450/bozvhajwaopkmhuuni7v.jpg", cooking_time: 15, difficulty_id: 1, cuisine_id: 15, category_id: 36, main_ingredient_id: 91, diet_id: 2},
  {author_id: 1, title: "Bellini", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532985768/b9xf93s9si4phnnzeryi.jpg", cooking_time: 5, difficulty_id: 1, cuisine_id: 2, category_id: 26, main_ingredient_id: 500, diet_id: 1}
])

IngredientAmount.create!([
  {recipe_id: 3, ingredient_id: 445, amount: 2, measuring_id: 1},
  {recipe_id: 3, ingredient_id: 446, amount: 2, measuring_id: 2},
  {recipe_id: 3, ingredient_id: 447, amount: 2, measuring_id: 4},
  {recipe_id: 3, ingredient_id: 56, amount: 6, measuring_id: 4},
  {recipe_id: 3, ingredient_id: 60, amount: 7, measuring_id: 4},
  {recipe_id: 3, ingredient_id: 117, amount: 2, measuring_id: 4},
  {recipe_id: 3, ingredient_id: 151, amount: 3, measuring_id: 7},
  {recipe_id: 3, ingredient_id: 160, amount: 7, measuring_id: 4},
  {recipe_id: 3, ingredient_id: 231, amount: 10, measuring_id: 1},
  {recipe_id: 3, ingredient_id: 347, amount: 1, measuring_id: 2},
  {recipe_id: 4, ingredient_id: 448, amount: 14, measuring_id: 4},
  {recipe_id: 4, ingredient_id: 449, amount: 8, measuring_id: 1},
  {recipe_id: 4, ingredient_id: 22, amount: 10, measuring_id: 7},
  {recipe_id: 4, ingredient_id: 184, amount: 5, measuring_id: 4},
  {recipe_id: 4, ingredient_id: 246, amount: 5, measuring_id: 1},
  {recipe_id: 4, ingredient_id: 285, amount: 4, measuring_id: 1},
  {recipe_id: 4, ingredient_id: 405, amount: 2, measuring_id: 7},
  {recipe_id: 6, ingredient_id: 456, amount: 1, measuring_id: 1},
  {recipe_id: 6, ingredient_id: 457, amount: 5, measuring_id: 4},
  {recipe_id: 6, ingredient_id: 458, amount: 2, measuring_id: 2},
  {recipe_id: 6, ingredient_id: 459, amount: 5, measuring_id: 7},
  {recipe_id: 6, ingredient_id: 460, amount: 1, measuring_id: 7},
  {recipe_id: 6, ingredient_id: 282, amount: 1, measuring_id: 7},
  {recipe_id: 6, ingredient_id: 347, amount: 1, measuring_id: 7},
  {recipe_id: 6, ingredient_id: 425, amount: 4, measuring_id: 1},
  {recipe_id: 6, ingredient_id: 433, amount: 1, measuring_id: 2},
  {recipe_id: 7, ingredient_id: 461, amount: 2, measuring_id: 6},
  {recipe_id: 7, ingredient_id: 462, amount: 1, measuring_id: 1},
  {recipe_id: 7, ingredient_id: 463, amount: 14, measuring_id: 4},
  {recipe_id: 7, ingredient_id: 121, amount: 3, measuring_id: 5},
  {recipe_id: 7, ingredient_id: 126, amount: 2, measuring_id: 2},
  {recipe_id: 7, ingredient_id: 165, amount: 2, measuring_id: 2},
  {recipe_id: 7, ingredient_id: 166, amount: 4, measuring_id: 7},
  {recipe_id: 7, ingredient_id: 169, amount: 2, measuring_id: 2},
  {recipe_id: 7, ingredient_id: 213, amount: 1, measuring_id: 7},
  {recipe_id: 7, ingredient_id: 250, amount: 2, measuring_id: 7},
  {recipe_id: 7, ingredient_id: 314, amount: 6, measuring_id: 7},
  {recipe_id: 7, ingredient_id: 347, amount: 2, measuring_id: 1},
  {recipe_id: 7, ingredient_id: 413, amount: 2, measuring_id: 2},
  {recipe_id: 7, ingredient_id: 419, amount: 2, measuring_id: 1},
  {recipe_id: 7, ingredient_id: 441, amount: 1, measuring_id: 5},
  {recipe_id: 7, ingredient_id: 451, amount: 2, measuring_id: 7},
  {recipe_id: 7, ingredient_id: 453, amount: 2, measuring_id: 2},
  {recipe_id: 8, ingredient_id: 464, amount: 1, measuring_id: 6},
  {recipe_id: 8, ingredient_id: 465, amount: 1, measuring_id: 5},
  {recipe_id: 8, ingredient_id: 466, amount: 1, measuring_id: 1},
  {recipe_id: 8, ingredient_id: 467, amount: 1, measuring_id: 7},
  {recipe_id: 8, ingredient_id: 468, amount: 1, measuring_id: 1},
  {recipe_id: 8, ingredient_id: 469, amount: 2, measuring_id: 5},
  {recipe_id: 8, ingredient_id: 470, amount: 4, measuring_id: 4},
  {recipe_id: 8, ingredient_id: 471, amount: 10, measuring_id: 7},
  {recipe_id: 8, ingredient_id: 56, amount: 1, measuring_id: 1},
  {recipe_id: 8, ingredient_id: 166, amount: 1, measuring_id: 7},
  {recipe_id: 8, ingredient_id: 169, amount: 3, measuring_id: 1},
  {recipe_id: 8, ingredient_id: 243, amount: 2, measuring_id: 2},
  {recipe_id: 8, ingredient_id: 248, amount: 1, measuring_id: 1},
  {recipe_id: 8, ingredient_id: 282, amount: 1, measuring_id: 7},
  {recipe_id: 8, ingredient_id: 347, amount: 1, measuring_id: 7},
  {recipe_id: 8, ingredient_id: 357, amount: 1, measuring_id: 7},
  {recipe_id: 8, ingredient_id: 369, amount: 5, measuring_id: 1},
  {recipe_id: 8, ingredient_id: 456, amount: 1, measuring_id: 1},
  {recipe_id: 9, ingredient_id: 472, amount: 17, measuring_id: 4},
  {recipe_id: 9, ingredient_id: 473, amount: 7, measuring_id: 4},
  {recipe_id: 9, ingredient_id: 474, amount: 5, measuring_id: 4},
  {recipe_id: 9, ingredient_id: 475, amount: 3, measuring_id: 1},
  {recipe_id: 9, ingredient_id: 213, amount: 2, measuring_id: 7},
  {recipe_id: 9, ingredient_id: 248, amount: 5, measuring_id: 1},
  {recipe_id: 9, ingredient_id: 282, amount: 1, measuring_id: 7},
  {recipe_id: 9, ingredient_id: 347, amount: 1, measuring_id: 7},
  {recipe_id: 10, ingredient_id: 476, amount: 1, measuring_id: 6},
  {recipe_id: 10, ingredient_id: 477, amount: 15, measuring_id: 7},
  {recipe_id: 10, ingredient_id: 478, amount: 2, measuring_id: 7},
  {recipe_id: 10, ingredient_id: 479, amount: 1, measuring_id: 2},
  {recipe_id: 10, ingredient_id: 480, amount: 1, measuring_id: 2},
  {recipe_id: 10, ingredient_id: 481, amount: 1, measuring_id: 7},
  {recipe_id: 10, ingredient_id: 126, amount: 1, measuring_id: 2},
  {recipe_id: 10, ingredient_id: 136, amount: 1, measuring_id: 1},
  {recipe_id: 10, ingredient_id: 165, amount: 1, measuring_id: 2},
  {recipe_id: 10, ingredient_id: 166, amount: 1, measuring_id: 7},
  {recipe_id: 10, ingredient_id: 169, amount: 2, measuring_id: 2},
  {recipe_id: 10, ingredient_id: 347, amount: 1, measuring_id: 2},
  {recipe_id: 10, ingredient_id: 419, amount: 2, measuring_id: 1},
  {recipe_id: 10, ingredient_id: 439, amount: 2, measuring_id: 1},
  {recipe_id: 10, ingredient_id: 453, amount: 1, measuring_id: 2},
  {recipe_id: 10, ingredient_id: 456, amount: 1, measuring_id: 1},
  {recipe_id: 12, ingredient_id: 488, amount: 9, measuring_id: 4},
  {recipe_id: 12, ingredient_id: 489, amount: 1, measuring_id: 7},
  {recipe_id: 12, ingredient_id: 26, amount: 18, measuring_id: 4},
  {recipe_id: 12, ingredient_id: 29, amount: 15, measuring_id: 5},
  {recipe_id: 12, ingredient_id: 75, amount: 1, measuring_id: 7},
  {recipe_id: 12, ingredient_id: 139, amount: 2, measuring_id: 1},
  {recipe_id: 12, ingredient_id: 148, amount: 1, measuring_id: 4},
  {recipe_id: 12, ingredient_id: 166, amount: 2, measuring_id: 7},
  {recipe_id: 12, ingredient_id: 250, amount: 1, measuring_id: 7},
  {recipe_id: 12, ingredient_id: 265, amount: 1, measuring_id: 4},
  {recipe_id: 12, ingredient_id: 282, amount: 1, measuring_id: 7},
  {recipe_id: 12, ingredient_id: 314, amount: 2, measuring_id: 7},
  {recipe_id: 12, ingredient_id: 347, amount: 1, measuring_id: 7},
  {recipe_id: 12, ingredient_id: 405, amount: 2, measuring_id: 7},
  {recipe_id: 12, ingredient_id: 419, amount: 2, measuring_id: 1},
  {recipe_id: 12, ingredient_id: 459, amount: 10, measuring_id: 7},
  {recipe_id: 13, ingredient_id: 490, amount: 2, measuring_id: 2},
  {recipe_id: 13, ingredient_id: 491, amount: 1, measuring_id: 5},
  {recipe_id: 13, ingredient_id: 492, amount: 14, measuring_id: 4},
  {recipe_id: 13, ingredient_id: 493, amount: 1, measuring_id: 7},
  {recipe_id: 13, ingredient_id: 15, amount: 4, measuring_id: 4},
  {recipe_id: 13, ingredient_id: 26, amount: 2, measuring_id: 6},
  {recipe_id: 13, ingredient_id: 60, amount: 12, measuring_id: 4},
  {recipe_id: 13, ingredient_id: 238, amount: 8, measuring_id: 4},
  {recipe_id: 13, ingredient_id: 248, amount: 2, measuring_id: 1},
  {recipe_id: 13, ingredient_id: 265, amount: 2, measuring_id: 2},
  {recipe_id: 13, ingredient_id: 282, amount: 1, measuring_id: 1},
  {recipe_id: 13, ingredient_id: 347, amount: 1, measuring_id: 2},
  {recipe_id: 13, ingredient_id: 357, amount: 1, measuring_id: 7},
  {recipe_id: 13, ingredient_id: 398, amount: 2, measuring_id: 2},
  {recipe_id: 14, ingredient_id: 494, amount: 2, measuring_id: 7},
  {recipe_id: 14, ingredient_id: 495, amount: 2, measuring_id: 2},
  {recipe_id: 14, ingredient_id: 496, amount: 1, measuring_id: 2},
  {recipe_id: 14, ingredient_id: 497, amount: 3, measuring_id: 2},
  {recipe_id: 14, ingredient_id: 498, amount: 2, measuring_id: 2},
  {recipe_id: 14, ingredient_id: 166, amount: 2, measuring_id: 7},
  {recipe_id: 14, ingredient_id: 169, amount: 2, measuring_id: 2},
  {recipe_id: 14, ingredient_id: 309, amount: 1, measuring_id: 6},
  {recipe_id: 14, ingredient_id: 332, amount: 2, measuring_id: 5},
  {recipe_id: 14, ingredient_id: 369, amount: 3, measuring_id: 1},
  {recipe_id: 14, ingredient_id: 378, amount: 1, measuring_id: 1},
  {recipe_id: 14, ingredient_id: 385, amount: 1, measuring_id: 2},
  {recipe_id: 14, ingredient_id: 441, amount: 1, measuring_id: 5},
  {recipe_id: 15, ingredient_id: 499, amount: 1, measuring_id: 1},
  {recipe_id: 15, ingredient_id: 18, amount: 1, measuring_id: 1},
  {recipe_id: 15, ingredient_id: 91, amount: 8, measuring_id: 4},
  {recipe_id: 15, ingredient_id: 212, amount: 4, measuring_id: 4},
  {recipe_id: 15, ingredient_id: 239, amount: 1, measuring_id: 2},
  {recipe_id: 15, ingredient_id: 248, amount: 3, measuring_id: 1},
  {recipe_id: 15, ingredient_id: 468, amount: 1, measuring_id: 2},
  {recipe_id: 16, ingredient_id: 500, amount: 8, measuring_id: 4},
  {recipe_id: 16, ingredient_id: 83, amount: 6, measuring_id: 4},
  {recipe_id: 5, ingredient_id: 151, amount: 4, measuring_id: 7},
  {recipe_id: 5, ingredient_id: 154, amount: 2, measuring_id: 4},
  {recipe_id: 5, ingredient_id: 166, amount: 4, measuring_id: 7},
  {recipe_id: 5, ingredient_id: 169, amount: 2, measuring_id: 1},
  {recipe_id: 5, ingredient_id: 250, amount: 2, measuring_id: 7},
  {recipe_id: 5, ingredient_id: 260, amount: 1, measuring_id: 1},
  {recipe_id: 5, ingredient_id: 265, amount: 1, measuring_id: 2},
  {recipe_id: 5, ingredient_id: 282, amount: 1, measuring_id: 1},
  {recipe_id: 5, ingredient_id: 347, amount: 1, measuring_id: 1},
  {recipe_id: 5, ingredient_id: 405, amount: 2, measuring_id: 7},
  {recipe_id: 5, ingredient_id: 419, amount: 2, measuring_id: 1},
  {recipe_id: 5, ingredient_id: 433, amount: 1, measuring_id: 1},
  {recipe_id: 5, ingredient_id: 450, amount: 1, measuring_id: 7},
  {recipe_id: 5, ingredient_id: 451, amount: 2, measuring_id: 7},
  {recipe_id: 5, ingredient_id: 452, amount: 1, measuring_id: 7},
  {recipe_id: 5, ingredient_id: 453, amount: 2, measuring_id: 1},
  {recipe_id: 5, ingredient_id: 454, amount: 28, measuring_id: 4},
  {recipe_id: 5, ingredient_id: 455, amount: 2, measuring_id: 4},
  {recipe_id: 1, ingredient_id: 53, amount: 1, measuring_id: 7},
  {recipe_id: 1, ingredient_id: 140, amount: 1, measuring_id: 1},
  {recipe_id: 1, ingredient_id: 243, amount: 2, measuring_id: 2},
  {recipe_id: 1, ingredient_id: 282, amount: 1, measuring_id: 1},
  {recipe_id: 1, ingredient_id: 347, amount: 1, measuring_id: 1},
  {recipe_id: 1, ingredient_id: 441, amount: 1, measuring_id: 3},
  {recipe_id: 1, ingredient_id: 442, amount: 3, measuring_id: 1},
  {recipe_id: 11, ingredient_id: 7, amount: 2, measuring_id: 1},
  {recipe_id: 11, ingredient_id: 166, amount: 4, measuring_id: 7},
  {recipe_id: 11, ingredient_id: 169, amount: 2, measuring_id: 1},
  {recipe_id: 11, ingredient_id: 191, amount: 1, measuring_id: 2},
  {recipe_id: 11, ingredient_id: 250, amount: 2, measuring_id: 7},
  {recipe_id: 11, ingredient_id: 385, amount: 2, measuring_id: 2},
  {recipe_id: 11, ingredient_id: 441, amount: 1, measuring_id: 3},
  {recipe_id: 11, ingredient_id: 482, amount: 2, measuring_id: 6},
  {recipe_id: 11, ingredient_id: 483, amount: 8, measuring_id: 1},
  {recipe_id: 11, ingredient_id: 484, amount: 2, measuring_id: 1},
  {recipe_id: 11, ingredient_id: 485, amount: 5, measuring_id: 1},
  {recipe_id: 11, ingredient_id: 486, amount: 3, measuring_id: 1},
  {recipe_id: 11, ingredient_id: 487, amount: 1, measuring_id: 7},
  {recipe_id: 2, ingredient_id: 94, amount: 6, measuring_id: 5},
  {recipe_id: 2, ingredient_id: 151, amount: 4, measuring_id: 7},
  {recipe_id: 2, ingredient_id: 282, amount: 1, measuring_id: 1},
  {recipe_id: 2, ingredient_id: 347, amount: 1, measuring_id: 1},
  {recipe_id: 2, ingredient_id: 369, amount: 1, measuring_id: 1},
  {recipe_id: 2, ingredient_id: 443, amount: 2, measuring_id: 7},
  {recipe_id: 2, ingredient_id: 444, amount: 1, measuring_id: 1}
])


Step.create!([
  {recipe_id: 3, num: 1, body: "Preheat the oven to 175°C/350°F and grease and flour a loaf pan. In a large bowl, beat the butter, brown sugar, vanilla sugar, and salt until fluffy. Add the eggs one at a time, then stream in the milk while mixing. In a separate bowl mix the flour, baking powder, and cocoa. Add the dry mixture to the wet while mixing on low speed until well combined. Add the chocolate chips and mix briefly to combine.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532972367/psid26c8bpkewokxdcuf.jpg"},
  {recipe_id: 3, num: 2, body: "Transfer the batter to the prepared loaf pan, smooth with a rubber spatula, and bake in the preheated oven for approx. 60 min. Remove the cake from the oven, and let cool for approx. 30 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532972374/jbzpobaidhzpcsutl3bc.jpg"},
  {recipe_id: 3, num: 3, body: "Meanwhile, melt the bittersweet couverture chocolate over a double boiler. Once cake has cooled, remove from the loaf pan and cover the top evenly in melted couverture. Enjoy!", image: "https://res.cloudinary.com/clustermass/image/upload/v1532972379/aptk29yoxoysaz4cohut.jpg"},
  {recipe_id: 4, num: 1, body: "Slice tomatoes and grate Gruyère cheese. Roll out pizza dough and an even number of equal-sized circles using the cookie cutter.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532972754/juki242gplsz3jyaxwxo.jpg"},
  {recipe_id: 4, num: 2, body: "Preheat waffle iron and grease with some oil. Add a circle of dough to the warm waffle iron, spread some tomato sauce on and top with sliced tomatoes, grated Gruyère cheese, fresh basil leaves, and pesto. Cover with another circle of dough, then close the waffle iron and cook for approx. 3 – 4 min. or until they are golden brown. Repeat with remaining dough and ingredients until everything is used up. Serve warm with tomato sauce as a dip. Enjoy!", image: "https://res.cloudinary.com/clustermass/image/upload/v1532972759/z7r9cqvgwvihhzjzycxp.jpg"},
  {recipe_id: 6, num: 1, body: "Add lemon juice, vodka, tomato juice, Worcestershire sauce, and Tabasco to a highball glass. Season with salt and pepper and fill with ice. Stir thoroughly.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532974081/odcxj5ivdn8jnznurom7.jpg"},
  {recipe_id: 6, num: 2, body: "Garnish a celery stick and lemon wedge. Enjoy!", image: "https://res.cloudinary.com/clustermass/image/upload/v1532974101/sof0ujn8t4h6kahhc76k.jpg"},
  {recipe_id: 7, num: 1, body: "Debone the chicken legs and set the bones aside for later use. Chop chicken into chunks, season with half of the salt, and set aside in a bowl. Finely dice the onions and mince the ginger and garlic. Remove the ends of the bell peppers, cut out the inner core, and slice into chunks. Peel potatoes and cut into chunks. Zest and juice the lime, reserving the zest for serving. Set all the vegetables aside.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532975235/xxwgrzrgt6demiksrvxo.jpg"},
  {recipe_id: 7, num: 2, body: "Heat the oil a large pot set over medium-high heat. Sear the chicken pieces until golden brown, approx. 5 min. Remove from the pot and set aside. Add the reserved bones to the pan and fry for approx. 1 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532975241/s77lamobx6rb7ez90gnc.jpg"},
  {recipe_id: 7, num: 3, body: "Add the onions, garlic, and ginger to the pot and sauté for approx. 2 min. with the chicken bones. Add the curry powder, cumin, coriander, garam masala, turmeric, and the cinnamon stick. Season with remaining salt, stir well, and cook approx. 2 min., or until fragrant.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532975273/sfpt55hx7gtfenlron4a.jpg"},
  {recipe_id: 7, num: 4, body: "Drain canned crushed tomatoes. Add water, the drained tomatoes, coconut milk, lime juice, bell peppers, and potatoes to the pot and stir well. Cook, covered, for approx. 15 min. Remove chicken bones, add seared chicken back to the pan, and let cook, uncovered, for approx. 5 min. more. Garnish with lime zest, and serve alone, or with rice. Enjoy!", image: "https://res.cloudinary.com/clustermass/image/upload/v1532975283/v5ymwt9ovrviyy77yjd4.jpg"},
  {recipe_id: 8, num: 1, body: "Defrost the peas. Remove the seeds from the chilli pepper and chop finely. Finely grate the ginger. Finely dice the garlic clove and shallot.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532976070/dvrctrkwpwfpozvdiz4y.jpg"},
  {recipe_id: 8, num: 2, body: "Sauté the ginger, garlic, and shallot with brown sugar and then add the pineapple juice to deglaze. Reduce to medium heat for approx. 8 – 10 min. or until about a third of the liquid remains.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532976085/j0xpgsg5pkqkxraxhxh6.jpg"},
  {recipe_id: 8, num: 3, body: "Add lemon juice, soy sauce, olive oil, mirin, and chopped chili pepper to the marinade and continue to simmer for approx. 5 – 7 min. Then, remove from heat and puree with a hand blender. Leave to cool at room temperature.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532976100/rd3qb7tppkxg4w6vcims.jpg"},
  {recipe_id: 8, num: 4, body: "Preheat the oven to 180°C/ 355°F. Slice the lamb saddles lengthwise into strips.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532976124/nrr7wanlabgvxclwiric.jpg"},
  {recipe_id: 8, num: 5, body: "Marinade the lamb strips with the cooled mixture for approx. 5 - 10 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532976139/js8fudj12q1twbzfw4aj.jpg"},
  {recipe_id: 8, num: 6, body: "Spear the lamb strips onto wooden skewers and cook in preheated oven at 180°C/ 355°F for approx. 10 – 12 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532976156/zir6wtxw1hyarnmut2v3.jpg"},
  {recipe_id: 8, num: 7, body: "Use a food processor to puree the defrosted peas with vegetable stock, mint, nutmeg, salt, and pepper. Sprinkle the lamb skewers with sesame seeds and place on the puree to serve.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532976169/mzi4ochllto4gt8gaddl.jpg"},
  {recipe_id: 9, num: 1, body: "almostexperimental\nwww.almost-experimental.de\n“Find more delicious vegan and gluten-free recipes on our blog.”\n\nAdd gluten-free spaghetti to a pot of salted water and cook according to package instructions, or until al dente.", image: nil},
  {recipe_id: 9, num: 2, body: "Meanwhile, quarter cherry tomatoes. Halve and juice limes. Slice lime for garnish, if desired. Wash and shake dry arugula.", image: nil},
  {recipe_id: 9, num: 3, body: "Drain spaghetti and add to a bowl, together with tomatoes, lime juice, capers, and olive oil. Mix well and season to taste with salt and pepper. Serve with arugula and lime slices. Enjoy!", image: nil},
  {recipe_id: 10, num: 1, body: "Cut chicken breast into cubes or strips. Add the chicken, salt, and lemon to a bowl, mix well, and set aside for approx. 10 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532977878/yyw2sirkvjvrmwx8nxw1.jpg"},
  {recipe_id: 10, num: 2, body: "Blanch almonds in boiling water for approx. 5 min., then peel. Add blanched almonds, yogurt, cream, green chili peppers, garlic, ginger, white pepper, chili powder, ground cumin, coriander, and garam masala to a blender and puree to a smooth paste. Add paste to the bowl with chicken and let marinate in the fridge for approx. 3 hrs.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532977884/melpaowrx0ikabnczhsa.jpg"},
  {recipe_id: 10, num: 3, body: "Add vegetable oil to a frying pan over medium heat, and fry chicken until cooked through. Alternatively, you can thread the chicken onto skewers and fry them on all sides. Serve warm with parathas. Enjoy!", image: "https://res.cloudinary.com/clustermass/image/upload/v1532977889/t8v0cwueiqoqbbq3qzal.jpg"},
  {recipe_id: 12, num: 1, body: "Add beef stock to a pot with the beef shank and let simmer over low heat for approx. 2 hrs.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532979441/l4n7yk5jyixxsfjzcwy6.jpg"},
  {recipe_id: 12, num: 2, body: "Cut a cross into the bottoms of the tomatoes. Bring water to boil in a small pot and blanch tomatoes until you see that the cut splits open, then remove the tomatoes with a slotted spoon and transfer to a bowl of ice water. Once cool enough to touch, gently pull the skin off the tomatoes and dice them. Finely chop dill and parsley and set aside for serving. Peel and chop onion, garlic, carrot, parsley root, and potatoes, and slice white cabbage. Heat vegetable oil in a large pot over medium heat and add onion, garlic, carrot, parsley root, potatoes, and white cabbage. Season with salt and pepper and fry for approx. 6 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532979448/xmf7h63bwghgwigib9er.jpg"},
  {recipe_id: 12, num: 3, body: "Remove beef shank from beef stock, dice, and set aside. Deglaze the fried vegetables with all the beef stock from the meat pot. Add peeled and diced tomatoes and let simmer for approx. 25 min. with the lid half on. Afterwards remove the lid, add the diced beef, and let simmer for approx. 5 min. more.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532979454/zkh4vesn8f80l2gn5rns.jpg"},
  {recipe_id: 12, num: 4, body: "Serve cabbage soup in bowls with a dollop of sour cream, a bay leaf, dill, parsley, and season with more pepper. Enjoy!", image: "https://res.cloudinary.com/clustermass/image/upload/v1532979459/yefhlcojexe42nu0bmhd.jpg"},
  {recipe_id: 13, num: 1, body: "Rub beef tenderloin with freshly ground pepper. Heat some olive oil in a large frying pan until hot but not smoking. Brown beef on all sides for approx. 10 - 12 min. Set aside to cool.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532983992/caidx4x0s0m9suiv2kcz.jpg"},
  {recipe_id: 13, num: 2, body: "Finely chop shallot. Pick herb leaves and chop roughly. Cut mushrooms into cubes.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532983999/kcefhk54drriiwamp1wi.jpg"},
  {recipe_id: 13, num: 3, body: "In a large frying pan, heat butter and remaining olive oil. Add shallot and mushrooms and sauté until translucent.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984005/xq27gkgeq7u4qmlvjnoq.jpg"},
  {recipe_id: 13, num: 4, body: "Deglaze with white wine. Add salt and chopped herbs. Continue to sauté for approx. 10 min. until the alcohol has evaporated. Remove from heat and allow to cool.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984013/lfjm006jln6rzovljsex.jpg"},
  {recipe_id: 13, num: 5, body: "Transfer mushroom mixture to a food processor. Blend until smooth.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984020/a4c7lxhlgzth6r0smg2q.jpg"},
  {recipe_id: 13, num: 6, body: "Lay out a large sheet of plastic wrap on a cutting board. Line up half of the bacon slices in the middle. Spread mushroom paste over bacon. Then place beef tenderloin on top. Spread the remaining mushroom paste over the beef and cover with bacon slices. Tightly wrap beef with mushroom paste and bacon by wrapping up the plastic wrap. Cool in refrigerator for approx. 30 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984027/oivc1hgjyp9tjbhwofxk.jpg"},
  {recipe_id: 13, num: 7, body: "Preheat oven to 180°C/350°F. On a lightly floured work surface, roll out puff pastry into a rectangle. Remove beef from the plastic wrap and place lengthwise in the middle. Wrap pastry around beef so long sides overlap. Fold in short sides and tightly seal.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984046/zsiuj22mo41yk5qbxgou.jpg"},
  {recipe_id: 13, num: 8, body: "Transfer to a lined baking sheet seam side down. Brush with egg yolk and bake in a preheated oven at 180°C/350°F for approx. 10 - 15 min. Then reduce heat to 120°C/250°F and continue to bake for approx. 10 more min. until golden. Remove from oven and allow to rest for approx. 10 min. Enjoy with a fresh salad or vegetables.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984052/fg3ishfwcpnwuoialvsw.jpg"},
  {recipe_id: 14, num: 1, body: "Freeze pork for approx. 20 min. Slice against the grain into thin strips (approx. 5 cm/2 in. long). Split leek lengthwise and chop green part into 1.25 cm/0.5 in. slices. Mince garlic and fresh ginger.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984926/ws0osyrpm23ny72tqmlw.jpg"},
  {recipe_id: 14, num: 2, body: "Combine some of the soy sauce and half of the cornstarch in a large mixing bowl. Add pork and toss to coat. Set aside to marinate for approx. 10 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984932/hv0xt3mxbcblbhubgykq.jpg"},
  {recipe_id: 14, num: 3, body: "Whisk water, remaining soy sauce, Sriracha, remaining cornstarch, sugar, and chicken flavor bouillon in a small bowl. Set aside.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984938/hs2osyjvf11wou6yf4w2.jpg"},
  {recipe_id: 14, num: 4, body: "Heat some of the oil in a wok or large nonstick skillet over medium-high heat and swirl to coat. When oil is hot and shimmering, add pork. Stir-fry for approx. 1 – 3 min., or just until no longer pink. Remove from wok.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984944/faeobfyhu0evjifne5dq.jpg"},
  {recipe_id: 14, num: 5, body: "Heat remaining oil in same wok and swirl to coat. Add sliced leeks and stir-fry for approx. 3 min., or until almost tender. Add minced garlic and ginger and fry for approx. 30 sec., or until fragrant. Add pork back to wok.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984949/qflwpoansaiul1ozw17e.jpg"},
  {recipe_id: 14, num: 6, body: "Stir in soy sauce mixture. Reduce heat to medium and cook for approx. 1 – 2 min., or until sauce thickens. Turn off the heat. Stir in toasted sesame oil and serve with hot rice. Enjoy!", image: "https://res.cloudinary.com/clustermass/image/upload/v1532984956/xodjrgk1owjfiaylri9a.jpg"},
  {recipe_id: 15, num: 1, body: "Dice chicken into small chunks. Heat a frying pan over medium-high heat, add the chicken and fry until cooked through. Set aside to cool until serving.", image: nil},
  {recipe_id: 15, num: 2, body: "Dice the avocado. Whisk together the mustard, balsamic vinegar, and olive oil in a bowl. To serve the salad, place the iceberg lettuce leaves in a dish, followed by the avocado, chicken, mustard vinaigrette, sesame seeds and crispy onions. Enjoy!", image: nil},
  {recipe_id: 16, num: 1, body: "Blend canned peaches in a food processor until smooth.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532985894/mbhy8cp4wd1lcb4lu0j7.jpg"},
  {recipe_id: 16, num: 2, body: "Add a few spoonfuls of the peach purée to each Champagne flute. Top with chilled Champagne and enjoy!", image: "https://res.cloudinary.com/clustermass/image/upload/v1532985901/tflo6w6w0nfn74o3nqdq.jpg"},
  {recipe_id: 5, num: 1, body: "Finely dice onion, garlic, ginger, and chili. Cut bell peppers into thin strips. Dice tomatoes.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532973527/wqfndjpsip6pimlwt7hr.jpg"},
  {recipe_id: 5, num: 2, body: "Heat some vegetable oil in a frying pan over medium heat. Add onion, garlic, chili, and bell pepper, and sauté until soft, approx. 6 - 8 min. Then add ginger, spicy paprika, and cumin and cook for another 2 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532973535/aoueu9ahworytlqpe7ks.jpg"},
  {recipe_id: 5, num: 3, body: "Add fresh tomatoes and canned tomatoes to the pan and lightly crush them with the cooking spoon.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532973551/cpfgriid1aj03nxiehto.jpg"},
  {recipe_id: 1, num: 1, body: "Bring water to a boil. In the meantime, cut broccoli into florets. Simmer broccoli for approx. 15 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532970684/ymi8hdoomxet9rzr2xtr.jpg"},
  {recipe_id: 1, num: 2, body: "Drain some of the water so that the broccoli remains just covered. Add the powdered vegetable broth, then blend everything with an immersion blender until smooth.", image: nil},
  {recipe_id: 1, num: 3, body: "Add crème fraîche and season with salt, pepper, and nutmeg. Enjoy!", image: nil},
  {recipe_id: 2, num: 1, body: "Finely slice scallions and set aside. If want to serve the soup with noodles, prepare them according to the package instructions.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532971190/aicb0fwvuf7fosiwcair.jpg"},
  {recipe_id: 2, num: 2, body: "Put the chicken stock and soy sauce in a large pot over medium-high heat and bring to a boil. Meanwhile, beat the eggs with some salt and pepper until well combined.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532971202/itiuwj5mm1omvfuod1nc.jpg"},
  {recipe_id: 5, num: 4, body: "Preheat oven to 190°C/375°F. Add vegetable broth and cook over medium heat, stirring occasionally, for approx. 20 min. Stir in Worcestershire sauce and season with salt and pepper.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532973565/t6cxn1fcigzzso8zgekv.jpg"},
  {recipe_id: 5, num: 5, body: "Crack eggs into pan. Then crumble feta on top. Transfer to oven and bake at 190°C/375°F for approx. 7 - 10 min. until eggs have set. Remove from oven and garnish with fresh parsley to serve.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532973579/u1rjtlhfrjfwbrbmajrh.jpg"},
  {recipe_id: 11, num: 1, body: "Fill a pot with water, add sea salt, and bring to a boil. Slice cabbage lengthwise into quarters and chop roughly into bite-sized pieces. Place in a bowl.", image: nil},
  {recipe_id: 11, num: 2, body: "Remove boiling water from heat pour over the cabbage. Let sit for approx. 10 min. before draining in a colander. Rinse well under cold water to remove excess salt and pat dry with a clean kitchen towel. Return cabbage to the bowl, add vinegar, and stir well to combine.", image: nil},
  {recipe_id: 11, num: 3, body: "To make the marinade, roughly chop onion and, if using, deseed and chop the red chili. Add to a food processor, followed by the ginger, garlic, Korean red chili pepper flakes, fish sauce, sugar, honey, and apple juice. Blend into a smooth paste.", image: nil},
  {recipe_id: 11, num: 4, body: "To serve, stir the marinade and most of the toasted sesame seeds, if using, through the kimchi until fully coated. Garnish with more sesame seeds and the sliced scallions. Enjoy immediately, let sit awhile at room temperature before serving, or store in the fridge in a sterilized glass jar—it should keep for approx. 3 weeks.", image: nil},
  {recipe_id: 2, num: 3, body: "When the chicken stock is boiling, adjust the heat so that it bubbles gently, not furiously. Pour the eggs into the stock in a slow stream, stirring constantly. It's important to keep stirring until the eggs are cooked, for approx. 1 – 2 min.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532971220/mjhp2nrhfgka1pbw66i9.jpg"},
  {recipe_id: 2, num: 4, body: "Stir in the chopped scallions and sesame oil. Taste and adjust the seasoning with more salt, pepper, soy sauce, or sesame oil.", image: "https://res.cloudinary.com/clustermass/image/upload/v1532971245/ln8a06ztdpgqkaxyypsy.jpg"},
  {recipe_id: 2, num: 5, body: "Add cooked noodles to a serving bowl and pour the soup over. ", image: "https://res.cloudinary.com/clustermass/image/upload/v1532971258/oopodvhpt7ht7d0eol5m.jpg"},
  {recipe_id: 2, num: 6, body: "Enjoy!", image: "https://res.cloudinary.com/clustermass/image/upload/v1532971278/s5pbqxpyz4kmdhrslxkp.jpg"}
])

Video.create!([
  {recipe_id: 5, author_id: 4, title: nil, video_url: "https://www.youtube.com/embed/ifWWRZSWS18"},
  {recipe_id: 11, author_id: 4, title: nil, video_url: "https://www.youtube.com/embed/0sX_wDCbeuU"},
  {recipe_id: 2, author_id: 4, title: nil, video_url: "https://www.youtube.com/embed/mD23uR0_DwU"}
])
