Category.create!([
  {name: "20-minute meals"},
  {name: "American"},
  {name: "Apple season"},
  {name: "Asian"},
  {name: "Asparagus"},
  {name: "Baking"},
  {name: "Bbq"},
  {name: "Beef"},
  {name: "Berry season"},
  {name: "Bread"},
  {name: "Breakfast"},
  {name: "British"},
  {name: "Brunch recipes"},
  {name: "Cake"},
  {name: "Casseroles"},
  {name: "Chicken"},
  {name: "Chinese"},
  {name: "Chocolate"},
  {name: "Christmas"},
  {name: "Christmas bakery"},
  {name: "Cocktails"},
  {name: "Comfort food"},
  {name: "Cookies"},
  {name: "Dessert"},
  {name: "Dinner party"},
  {name: "Drink"},
  {name: "Easter"},
  {name: "European"},
  {name: "Family favorites"},
  {name: "Finger food"},
  {name: "Fourth of july"},
  {name: "French"},
  {name: "Frozen treats"},
  {name: "Game day"},
  {name: "German"},
  {name: "Greek"},
  {name: "Indian"},
  {name: "Italian"},
  {name: "Jewish"},
  {name: "Low carb"},
  {name: "Main course"},
  {name: "Main"},
  {name: "Mardi gras"},
  {name: "Meatless"},
  {name: "Mediterranean"},
  {name: "Mexican"},
  {name: "Middle-eastern"},
  {name: "Mother's day"},
  {name: "No-bake desserts"},
  {name: "One-pot"},
  {name: "Packed lunch"},
  {name: "Pasta"},
  {name: "Pies and tarts"},
  {name: "Pizza"},
  {name: "Potatoes"},
  {name: "Potluck"},
  {name: "Prep ahead"},
  {name: "Pumpkin"},
  {name: "Quick bites"},
  {name: "Quick dessert"},
  {name: "Recipes for fall"},
  {name: "Recipes for spring"},
  {name: "Recipes for summer"},
  {name: "Recipes for winter"},
  {name: "Refreshments"},
  {name: "Salads"},
  {name: "Seafood"},
  {name: "Soup"},
  {name: "Snack"},
  {name: "Starter"},
  {name: "Strawberry season"},
  {name: "Thanksgiving"},
  {name: "Under 400 calories"},
  {name: "Under 7 ingredients"},
  {name: "Valentine's day"},
  {name: "Vegan"},
  {name: "Vegetarian"},
  {name: "Vietnamese"},
  {name: "Wedding season"},
  {name: "Weeknight dinners"}
])
Cuisine.create!([
  {sort: "Traditional", country: "China"},
  {sort: "Traditional", country: "Italy"},
  {sort: "Traditional", country: "India"},
  {sort: "Traditional", country: "Spain"},
  {sort: "Traditional", country: "America"},
  {sort: "Traditional", country: "East"},
  {sort: "Traditional", country: "Asia"},
  {sort: "Traditional", country: "France"},
  {sort: "Traditional", country: "Europe"},
  {sort: "Other", country: "Other"}
])
Diet.create!([
  {name: "Regular"},
  {name: "Low-fat"},
  {name: "Vegetarian"},
  {name: "Vegan"},
  {name: "Sugar-free"},
  {name: "Lactose-free"},
  {name: "Gluten-free"},
  {name: "Alcohol-free"}
])
Difficulty.create!([
  {level: "Easy"},
  {level: "Medium"},
  {level: "Hard"}
])
Ingredient.create!([
  {name: "spice"},
  {name: "almond"},
  {name: "all-purpose flour"},
  {name: "amaretti"},
  {name: "anchovy"},
  {name: "anise"},
  {name: "apple juice"},
  {name: "artichoke"},
  {name: "artichoke heart"},
  {name: "artichoke"},
  {name: "asparagus"},
  {name: "asparagus spear"},
  {name: "aubergine"},
  {name: "avocado"},
  {name: "bacon"},
  {name: "baguette"},
  {name: "baked beans"},
  {name: "balsamic vinegar"},
  {name: "bamboo"},
  {name: "banana"},
  {name: "bap"},
  {name: "basil"},
  {name: "bay leaf"},
  {name: "bay leaves"},
  {name: "bean"},
  {name: "beef"},
  {name: "beef mince"},
  {name: "beef brisket"},
  {name: "beef stock"},
  {name: "bell pepper"},
  {name: "berry"},
  {name: "berries"},
  {name: "bicarbonate of soda"},
  {name: "biscuit"},
  {name: "biscuit"},
  {name: "black olive"},
  {name: "black pepper"},
  {name: "black-eyed peas"},
  {name: "blueberries"},
  {name: "blueberry"},
  {name: "bonnet chilli"},
  {name: "bouillon"},
  {name: "bourbon"},
  {name: "braising steak"},
  {name: "bran"},
  {name: "brandy"},
  {name: "bread"},
  {name: "breadcrumbs"},
  {name: "bbq sauce"},
  {name: "habanero sauce"},
  {name: "brie"},
  {name: "brine"},
  {name: "broccoli"},
  {name: "brown rice"},
  {name: "brown sauce"},
  {name: "brown sugar"},
  {name: "buckwheat"},
  {name: "buffalo"},
  {name: "bun"},
  {name: "butter"},
  {name: "buttermilk"},
  {name: "butternut"},
  {name: "butternut squash"},
  {name: "butterscotch"},
  {name: "cabbage"},
  {name: "cake"},
  {name: "candy"},
  {name: "candies"},
  {name: "cannellini"},
  {name: "canola oil"},
  {name: "caper"},
  {name: "caramel"},
  {name: "caraway seed"},
  {name: "cardamom"},
  {name: "carrot"},
  {name: "carrot"},
  {name: "cashew"},
  {name: "caster sugar"},
  {name: "cayenne pepper"},
  {name: "celeriac"},
  {name: "celery"},
  {name: "cereal"},
  {name: "champagne"},
  {name: "chard"},
  {name: "cheddar cheese"},
  {name: "cheese"},
  {name: "cherries"},
  {name: "cherry"},
  {name: "cherry tomatoe"},
  {name: "chestnut"},
  {name: "chicken"},
  {name: "chicken breast"},
  {name: "chicken drumstick"},
  {name: "chicken stock"},
  {name: "chicken thigh"},
  {name: "chicken leg"},
  {name: "chicken"},
  {name: "chickpea"},
  {name: "chicory"},
  {name: "chile"},
  {name: "chilli"},
  {name: "chillies"},
  {name: "chipotle"},
  {name: "chip"},
  {name: "chive"},
  {name: "chive"},
  {name: "chocolate"},
  {name: "chop"},
  {name: "choy"},
  {name: "chutney"},
  {name: "ciabatta"},
  {name: "cider"},
  {name: "cinnamon"},
  {name: "clam"},
  {name: "clarified butter"},
  {name: "clove"},
  {name: "cocoa"},
  {name: "coconut"},
  {name: "orange essence"},
  {name: "almond essence"},
  {name: "coconut milk"},
  {name: "cod"},
  {name: "coffee"},
  {name: "coleslaw"},
  {name: "condensed milk"},
  {name: "coriander"},
  {name: "coriander leaves"},
  {name: "corn"},
  {name: "cornflour"},
  {name: "cornmeal"},
  {name: "courgette"},
  {name: "couscous"},
  {name: "cranberries"},
  {name: "cranberry"},
  {name: "cranberry juice"},
  {name: "cream"},
  {name: "single cream"},
  {name: "double cream"},
  {name: "sour cream"},
  {name: "creme fraiche"},
  {name: "crisp"},
  {name: "crust"},
  {name: "creme de cassis"},
  {name: "cucumber"},
  {name: "cumin"},
  {name: "custard"},
  {name: "dijon mustard"},
  {name: "dill"},
  {name: "duck"},
  {name: "edamame bean"},
  {name: "egg"},
  {name: "espresso"},
  {name: "fennel"},
  {name: "feta"},
  {name: "fig"},
  {name: "fillet steak"},
  {name: "filo pastry"},
  {name: "fish"},
  {name: "flank"},
  {name: "flour"},
  {name: "focaccia"},
  {name: "foie gras"},
  {name: "fruit"},
  {name: "fudge"},
  {name: "garam masala"},
  {name: "garlic"},
  {name: "gelatine"},
  {name: "gin"},
  {name: "ginger"},
  {name: "glucose"},
  {name: "goat"},
  {name: "goat's cheese"},
  {name: "golden syrup"},
  {name: "gorgonzola"},
  {name: "gouda"},
  {name: "grape"},
  {name: "grapefruit"},
  {name: "grape"},
  {name: "grapeseed"},
  {name: "green olive"},
  {name: "green pepper"},
  {name: "green"},
  {name: "gruyere"},
  {name: "gruyere cheese"},
  {name: "haddock"},
  {name: "ham"},
  {name: "harissa"},
  {name: "herbs"},
  {name: "hoisin"},
  {name: "hoisin sauce"},
  {name: "honey"},
  {name: "honeydew melon"},
  {name: "horseradish"},
  {name: "iceberg lettuce"},
  {name: "icing sugar"},
  {name: "jalapeno pepper"},
  {name: "juice"},
  {name: "julienne"},
  {name: "kalamata olives"},
  {name: "ketchup"},
  {name: "kidney bean"},
  {name: "lager"},
  {name: "lamb"},
  {name: "lard"},
  {name: "lardons"},
  {name: "lasagne"},
  {name: "lavender"},
  {name: "leek"},
  {name: "lemon"},
  {name: "lemongrass"},
  {name: "lentil"},
  {name: "lettuce"},
  {name: "lime"},
  {name: "limoncello"},
  {name: "lobster"},
  {name: "loin"},
  {name: "lychee"},
  {name: "macadamia nut"},
  {name: "malt"},
  {name: "mangetout"},
  {name: "mango"},
  {name: "mangoes"},
  {name: "maple syrup"},
  {name: "marinara"},
  {name: "marshmallow"},
  {name: "marzano"},
  {name: "mascarpone"},
  {name: "mayonnaise"},
  {name: "meat"},
  {name: "melon"},
  {name: "milk"},
  {name: "mince"},
  {name: "mint"},
  {name: "miso soup"},
  {name: "molasses"},
  {name: "monterey jack"},
  {name: "mozzarella"},
  {name: "mushroom"},
  {name: "mustard"},
  {name: "new potato"},
  {name: "noodle"},
  {name: "nutella"},
  {name: "nutmeg"},
  {name: "nut"},
  {name: "oat"},
  {name: "oil"},
  {name: "okra"},
  {name: "olive oil"},
  {name: "olive"},
  {name: "onion"},
  {name: "onion ring"},
  {name: "orange"},
  {name: "orange juice"},
  {name: "oregano"},
  {name: "oyster"},
  {name: "pak choi"},
  {name: "pancetta"},
  {name: "panko"},
  {name: "papaya"},
  {name: "paprika"},
  {name: "parma ham"},
  {name: "parmesan"},
  {name: "parmigiano"},
  {name: "parmigiano-reggiano"},
  {name: "parsley"},
  {name: "parsnip"},
  {name: "passion fruit"},
  {name: "pasta"},
  {name: "pasta shell"},
  {name: "pastry"},
  {name: "pea"},
  {name: "peach"},
  {name: "peaches"},
  {name: "peanut"},
  {name: "peanut"},
  {name: "pear"},
  {name: "pea"},
  {name: "pecan"},
  {name: "pecorino"},
  {name: "penne"},
  {name: "penne pasta"},
  {name: "pepper"},
  {name: "peppercorn"},
  {name: "peppers"},
  {name: "pesto"},
  {name: "pickle"},
  {name: "pickled gherkin"},
  {name: "pickled onion"},
  {name: "pickled red onion"},
  {name: "pie"},
  {name: "pimento pepper"},
  {name: "pine nut"},
  {name: "pineapple"},
  {name: "pistachio"},
  {name: "pita"},
  {name: "pitta"},
  {name: "pitted olive"},
  {name: "pizza"},
  {name: "plantain"},
  {name: "plum"},
  {name: "plum tomato"},
  {name: "plum tomatoes"},
  {name: "sun dried tomato"},
  {name: "poblano"},
  {name: "pod"},
  {name: "polenta"},
  {name: "pomegranate"},
  {name: "popcorn"},
  {name: "pork"},
  {name: "pork chop"},
  {name: "porridge"},
  {name: "poultry"},
  {name: "potato"},
  {name: "potatoes"},
  {name: "prawn"},
  {name: "prosciutto"},
  {name: "prosciutto ham"},
  {name: "provolone"},
  {name: "pumpkin"},
  {name: "quail"},
  {name: "radicchio"},
  {name: "radish"},
  {name: "radishes"},
  {name: "rapeseed oil"},
  {name: "raspberries"},
  {name: "raspberry"},
  {name: "red pepper"},
  {name: "red onion"},
  {name: "relish"},
  {name: "rhubarb"},
  {name: "rib"},
  {name: "rice"},
  {name: "ricotta"},
  {name: "rocket"},
  {name: "roll"},
  {name: "rose"},
  {name: "rosemary"},
  {name: "russet"},
  {name: "saffron"},
  {name: "sage"},
  {name: "sake"},
  {name: "salad"},
  {name: "salami"},
  {name: "salmon"},
  {name: "salmon flake"},
  {name: "salsa"},
  {name: "salt"},
  {name: "sauce"},
  {name: "sausage"},
  {name: "savoy cabbage"},
  {name: "scallop"},
  {name: "schnapps"},
  {name: "self raising flour"},
  {name: "semolina"},
  {name: "seafood"},
  {name: "serrano ham"},
  {name: "shallot"},
  {name: "shaohsing"},
  {name: "sherry"},
  {name: "shiitake"},
  {name: "shiitake mushroom"},
  {name: "shortcrust pastry"},
  {name: "sirloin"},
  {name: "sirloin steak"},
  {name: "slaw"},
  {name: "smoky bacon"},
  {name: "snapper"},
  {name: "sourdough"},
  {name: "soy sauce"},
  {name: "spaghetti"},
  {name: "spice"},
  {name: "spinach"},
  {name: "sponge"},
  {name: "spring onion"},
  {name: "sprout"},
  {name: "squash"},
  {name: "squid"},
  {name: "sriracha"},
  {name: "steak"},
  {name: "stock"},
  {name: "stout"},
  {name: "strawberries"},
  {name: "strawberry"},
  {name: "stuffing"},
  {name: "sugar"},
  {name: "sultana"},
  {name: "sunflower oil"},
  {name: "sweet pepper"},
  {name: "sweetcorn"},
  {name: "sweets"},
  {name: "swordfish"},
  {name: "tangerine"},
  {name: "tapioca"},
  {name: "tarragon"},
  {name: "tartar"},
  {name: "tea"},
  {name: "tequila"},
  {name: "thyme"},
  {name: "toast"},
  {name: "toffee"},
  {name: "tofu"},
  {name: "tomatillos"},
  {name: "tomato"},
  {name: "tomato puree"},
  {name: "tomatoes"},
  {name: "tortilla"},
  {name: "treacle"},
  {name: "tuna steak"},
  {name: "tuna"},
  {name: "turkey"},
  {name: "turkey breast"},
  {name: "turkey thigh"},
  {name: "turmeric"},
  {name: "turnip"},
  {name: "vanilla"},
  {name: "vanilla essence"},
  {name: "vanilla pod"},
  {name: "veal"},
  {name: "vegetable oil"},
  {name: "vermouth"},
  {name: "vinaigrette"},
  {name: "vinegar"},
  {name: "white wine vinegar"},
  {name: "red wine vinegar"},
  {name: "vodka"},
  {name: "waffle"},
  {name: "walnut"},
  {name: "watercress"},
  {name: "watermelon"},
  {name: "white rice"},
  {name: "wholegrain pasta"},
  {name: "wine"},
  {name: "worcestershire sauce"},
  {name: "yeast"},
  {name: "yellow pepper"},
  {name: "greek yoghurt"},
  {name: "natural yoghurt"},
  {name: "yoghurt"},
  {name: "yogurt"},
  {name: "red onion"}
])

User.create!([
  {username: "1", password_digest: "$2a$10$mAOlZxUw7Ur3tUXracf1FuweaklOb60mc.oQmb0B4E1Ks13MCHb/e", name: "Tom McAnderson", session_token: "4xTSXRAGxrcy_e7muNBYNw"},
  {username: "2", password_digest: "$2a$10$k.8UHoa/a40p7Vb3tnDuN.OTSZx52S3TUra9TFaxhbaY9a/002PJ6", name: "Kate Jhonson", session_token: "LidWypT6OSY32v6_v6PuZw"},
  {username: "3", password_digest: "$2a$10$WCBjgsCoR/GtySF05o0eTeHPD4x8MhTQnHRMTN4whivWzu.Si50N.", name: "Stephen Luciani", session_token: "d4qouTewp-fkj0KOMGb3yA"},
  {username: "demo", password_digest: "$2a$10$kiBN4yrHoczHc12ZQJhz9O5w1DnEhRTJcATRUqRgQVFGCNE1TzSYu", name: "Demo User", session_token: "tq-0UoEiEQHPHLbIk68sQQ"}
])

Measuring.create!([
  {name: "tablespoon"},
  {name: "teaspoon"},
  {name: "quart"},
  {name: "oz"},
  {name: "cup"},
  {name: "lb"},
  {name: "pcs"}
])


Recipe.create!([
  {author_id: 1, title: "Shakshuka", main_picture_url: "https://res.cloudinary.com/clustermass/image/upload/v1532892450/nsct6nv5eolzodrzaqei.jpg", cooking_time: 20, difficulty_id: 1, cuisine_id: 7, category_id: 1, main_ingredient_id: 151, diet_id: 1}
])

IngredientAmount.create!([
  {recipe_id: 1, ingredient_id: 151, amount: 5, measuring_id: 7},
  {recipe_id: 1, ingredient_id: 265, amount: 1, measuring_id: 5}
])

Step.create!([
  {recipe_id: 1, num: 1, body: "Finely dice onion, garlic, ginger, and chili. Cut bell peppers into thin strips. Dice tomatoes.", image: nil}
])
